name: CI
on:
  repository_dispatch:
    types:
      - webhook-1
      - webhook-2
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools
          set PATH=${PWD}/depot_tools:$PATH
          set DEPOT_TOOLS_WIN_TOOLCHAIN=0
          gclient config --unmanaged https://pdfium.googlesource.com/pdfium.git
          gclient sync
          cd pdfium
          git clean -dfx
          git reset --hard 467e8dde57c687bb7ec9452fa2620f000cfe849a
          cd ../
          gclient sync
          
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up environment
        run: echo "RELEASE_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Install GitHub CLI
        uses: sersoft-gmbh/setup-gh-cli-action@v2

      - name: Delete existing release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release delete $RELEASE_DATE --yes || true

      - name: Create new release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create $RELEASE_DATE -t "Release $RELEASE_DATE" -n "Automated release for $RELEASE_DATE"

      - name: Download Artifacts
        run: |
          mkdir -p ./artifacts
          wget -O ./artifacts/x64_rel_md_no_v8.zip https://download.happygogo.site/x64_rel_md_no_v8.zip
          wget -O ./artifacts/x64_dbg_md_no_v8.zip https://download.happygogo.site/x64_dbg_md_no_v8.zip
          wget -O ./artifacts/x64_rel_no_v8.zip https://download.happygogo.site/x64_rel_no_v8.zip
          wget -O ./artifacts/x64_dbg_no_v8.zip https://download.happygogo.site/x64_dbg_no_v8.zip



      - name: List Zipped Files
        run: ls ./artifacts/*.zip

      - name: Generate MD5 Checksums
        run: |
          > ./artifacts/filelist.txt  # 清空或创建 filelist.txt 文件
          for file in ./artifacts/*.zip; do
            # Calculate MD5 checksum
            md5sum=$(md5sum "$file" | awk '{ print $1 }')
            
            # Write to filelist.txt
            echo "$(basename "$file") | ${md5sum}" >> ./artifacts/filelist.txt
          done

      - name: Upload Artifacts to Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ./artifacts
          gh release upload $RELEASE_DATE ./*.zip
          gh release upload $RELEASE_DATE ./filelist.txt
